import Footer from "@/components/organism/Footer";
import Header from "@/components/organism/Header";
import "@/styles/globals.css";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Shoesped Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}
